namespace DerbyDash.Components.Layout {
    public static partial class BreadcrumbLinks {
        private static Dictionary<string, BreadcrumbLinksItem> BreadcrumbLinksDictionary { get; set; } = new Dictionary<string, BreadcrumbLinksItem> {
            { "racesetsmenu", new BreadcrumbLinksItem { Title = "Races", Url = "/RaceSetsMenu", Parent = ""} },
            { "addition-1digitsimple", new BreadcrumbLinksItem { Title = "1 Digit, Simple", Url = "/race/addition-1digitsimple", Parent = "Addition-ProblemsMenu"} },
            { "addition-1digit", new BreadcrumbLinksItem { Title = "1 Digit", Url = "/race/addition-1digit", Parent = "Addition-ProblemsMenu"} },
            { "addition-12digitsimple", new BreadcrumbLinksItem { Title = "1 and 2 Digit, Simple", Url = "/race/addition-12digitsimple", Parent = "Addition-ProblemsMenu"} },
            { "addition-12digit", new BreadcrumbLinksItem { Title = "1 and 2 Digit", Url = "/race/addition-12digit", Parent = "Addition-ProblemsMenu"} },
            { "addition-2digitsimple", new BreadcrumbLinksItem { Title = "2 Digit, simple", Url = "/race/addition-2digitsimple", Parent = "Addition-ProblemsMenu"} },
            { "addition-2digit", new BreadcrumbLinksItem { Title = "2 digit", Url = "/race/addition-2digit", Parent = "Addition-ProblemsMenu"} },
            { "addition-3digitsimple", new BreadcrumbLinksItem { Title = "3 digit, simple", Url = "/race/addition-3digitsimple", Parent = "Addition-ProblemsMenu"} },
            { "addition-3digit", new BreadcrumbLinksItem { Title = "3 digit", Url = "/race/addition-3digit", Parent = "Addition-ProblemsMenu"} },
            { "addition-1stable", new BreadcrumbLinksItem { Title = "1s Table", Url = "/race/addition-1stable", Parent = "Addition-TablesMenu"} },
            { "addition-2stable", new BreadcrumbLinksItem { Title = "2s Table", Url = "/race/addition-2stable", Parent = "Addition-TablesMenu"} },
            { "addition-3stable", new BreadcrumbLinksItem { Title = "3s Table", Url = "/race/addition-3stable", Parent = "Addition-TablesMenu"} },
            { "addition-4stable", new BreadcrumbLinksItem { Title = "4s Table", Url = "/race/addition-4stable", Parent = "Addition-TablesMenu"} },
            { "addition-5stable", new BreadcrumbLinksItem { Title = "5s Table", Url = "/race/addition-5stable", Parent = "Addition-TablesMenu"} },
            { "addition-6stable", new BreadcrumbLinksItem { Title = "6s Table", Url = "/race/addition-6stable", Parent = "Addition-TablesMenu"} },
            { "addition-7stable", new BreadcrumbLinksItem { Title = "7s Table", Url = "/race/addition-7stable", Parent = "Addition-TablesMenu"} },
            { "addition-8stable", new BreadcrumbLinksItem { Title = "8s Table", Url = "/race/addition-8stable", Parent = "Addition-TablesMenu"} },
            { "addition-9stable", new BreadcrumbLinksItem { Title = "9s Table", Url = "/race/addition-9stable", Parent = "Addition-TablesMenu"} },
            { "addition-10stable", new BreadcrumbLinksItem { Title = "10s Table", Url = "/race/addition-10stable", Parent = "Addition-TablesMenu"} },
            { "addition-11stable", new BreadcrumbLinksItem { Title = "11s Table", Url = "/race/addition-11stable", Parent = "Addition-TablesMenu"} },
            { "addition-12stable", new BreadcrumbLinksItem { Title = "12s Table", Url = "/race/addition-12stable", Parent = "Addition-TablesMenu"} },
            { "addition-13stable", new BreadcrumbLinksItem { Title = "13s Table", Url = "/race/addition-13stable", Parent = "Addition-TablesMenu"} },
            { "addition-tablesmenu", new BreadcrumbLinksItem { Title = "Addition Tables", Url = "/Addition-TablesMenu", Parent = "AdditionMenu"} },
            { "addition-problemsmenu", new BreadcrumbLinksItem { Title = "Mixed Problem Sets", Url = "/Addition-ProblemsMenu", Parent = "AdditionMenu"} },
            { "multiplication-1digitsimple", new BreadcrumbLinksItem { Title = "1 Digit, Simple", Url = "/race/multiplication-1digitsimple", Parent = "Multiplication-ProblemsMenu"} },
            { "multiplication-1digit", new BreadcrumbLinksItem { Title = "1 Digit", Url = "/race/multiplication-1digit", Parent = "Multiplication-ProblemsMenu"} },
            { "multiplication-12digitsimple", new BreadcrumbLinksItem { Title = "1 and 2 Digit, Simple", Url = "/race/multiplication-12digitsimple", Parent = "Multiplication-ProblemsMenu"} },
            { "multiplication-12digit", new BreadcrumbLinksItem { Title = "1 and 2 Digit", Url = "/race/multiplication-12digit", Parent = "Multiplication-ProblemsMenu"} },
            { "multiplication-2digitsimple", new BreadcrumbLinksItem { Title = "2 Digit, simple", Url = "/race/multiplication-2digitsimple", Parent = "Multiplication-ProblemsMenu"} },
            { "multiplication-2digit", new BreadcrumbLinksItem { Title = "2 digit", Url = "/race/multiplication-2digit", Parent = "Multiplication-ProblemsMenu"} },
            { "multiplication-3digitsimple", new BreadcrumbLinksItem { Title = "3 digit, simple", Url = "/race/multiplication-3digitsimple", Parent = "Multiplication-ProblemsMenu"} },
            { "multiplication-3digit", new BreadcrumbLinksItem { Title = "3 digit", Url = "/race/multiplication-3digit", Parent = "Multiplication-ProblemsMenu"} },
            { "multiplication-squaressmall", new BreadcrumbLinksItem { Title = "Squares, small", Url = "/race/multiplication-squaressmall", Parent = "Multiplication-ProblemsMenu"} },
            { "multiplication-squareslarge", new BreadcrumbLinksItem { Title = "Squares, large", Url = "/race/multiplication-squareslarge", Parent = "Multiplication-ProblemsMenu"} },
            { "multiplication-2stable", new BreadcrumbLinksItem { Title = "2s Table", Url = "/race/multiplication-2stable", Parent = "Multiplication-TablesMenu"} },
            { "multiplication-3stable", new BreadcrumbLinksItem { Title = "3s Table", Url = "/race/multiplication-3stable", Parent = "Multiplication-TablesMenu"} },
            { "multiplication-4stable", new BreadcrumbLinksItem { Title = "4s Table", Url = "/race/multiplication-4stable", Parent = "Multiplication-TablesMenu"} },
            { "multiplication-5stable", new BreadcrumbLinksItem { Title = "5s Table", Url = "/race/multiplication-5stable", Parent = "Multiplication-TablesMenu"} },
            { "multiplication-6stable", new BreadcrumbLinksItem { Title = "6s Table", Url = "/race/multiplication-6stable", Parent = "Multiplication-TablesMenu"} },
            { "multiplication-7stable", new BreadcrumbLinksItem { Title = "7s Table", Url = "/race/multiplication-7stable", Parent = "Multiplication-TablesMenu"} },
            { "multiplication-8stable", new BreadcrumbLinksItem { Title = "8s Table", Url = "/race/multiplication-8stable", Parent = "Multiplication-TablesMenu"} },
            { "multiplication-9stable", new BreadcrumbLinksItem { Title = "9s Table", Url = "/race/multiplication-9stable", Parent = "Multiplication-TablesMenu"} },
            { "multiplication-10stable", new BreadcrumbLinksItem { Title = "10s Table", Url = "/race/multiplication-10stable", Parent = "Multiplication-TablesMenu"} },
            { "multiplication-11stable", new BreadcrumbLinksItem { Title = "11s Table", Url = "/race/multiplication-11stable", Parent = "Multiplication-TablesMenu"} },
            { "multiplication-12stable", new BreadcrumbLinksItem { Title = "12s Table", Url = "/race/multiplication-12stable", Parent = "Multiplication-TablesMenu"} },
            { "multiplication-13stable", new BreadcrumbLinksItem { Title = "13s Table", Url = "/race/multiplication-13stable", Parent = "Multiplication-TablesMenu"} },
            { "multiplication-tablesmenu", new BreadcrumbLinksItem { Title = "Multiplication Tables", Url = "/Multiplication-TablesMenu", Parent = "MultiplicationMenu"} },
            { "multiplication-problemsmenu", new BreadcrumbLinksItem { Title = "Mixed Problem Sets", Url = "/Multiplication-ProblemsMenu", Parent = "MultiplicationMenu"} },
            { "race#keyboardingrace", new BreadcrumbLinksItem { Title = "Keyboarding", Url = "/race#Keyboardingrace", Parent = "RaceSetsMenu"} },
            { "additionmenu", new BreadcrumbLinksItem { Title = "Addition", Url = "/AdditionMenu", Parent = "RaceSetsMenu"} },
            { "subtractionmenu", new BreadcrumbLinksItem { Title = "Subtraction", Url = "/SubtractionMenu", Parent = "RaceSetsMenu"} },
            { "multiplicationmenu", new BreadcrumbLinksItem { Title = "Multiplication", Url = "/MultiplicationMenu", Parent = "RaceSetsMenu"} },
            { "divisionmenu", new BreadcrumbLinksItem { Title = "Division", Url = "/DivisionMenu", Parent = "RaceSetsMenu"} },
            { "fractionsmenu", new BreadcrumbLinksItem { Title = "Fractions", Url = "/FractionsMenu", Parent = "RaceSetsMenu"} },
            { "decimalsmenu", new BreadcrumbLinksItem { Title = "Decimals", Url = "/DecimalsMenu", Parent = "RaceSetsMenu"} },
            { "subscription", new BreadcrumbLinksItem { Title = "Subscription", Url = "/Account/Manage/Subscription", Parent = "Account/Manage"} }
        };
    }
}
