namespace DerbyDash.Problems {
    public class AdditionMixedSimple: AdditionProblemsBase {
        protected int MaxWTen = 69;
        protected int MaxWoTen = 54;

        public AdditionMixedSimple() : base() { }

        public static readonly Operands[] Items = new Operands[] {
            new Operands(1, 1),
            new Operands(1, 2),
            new Operands(1, 3),
            new Operands(1, 4),
            new Operands(1, 5),
            new Operands(1, 6),
            new Operands(1, 7),
            new Operands(1, 8),
            new Operands(2, 1),
            new Operands(2, 2),
            new Operands(2, 3),
            new Operands(2, 4),
            new Operands(2, 5),
            new Operands(2, 6),
            new Operands(2, 7),
            new Operands(3, 1),
            new Operands(3, 2),
            new Operands(3, 3),
            new Operands(3, 4),
            new Operands(3, 5),
            new Operands(3, 6),
            new Operands(4, 1),
            new Operands(4, 2),
            new Operands(4, 3),
            new Operands(4, 4),
            new Operands(4, 5),
            new Operands(5, 1),
            new Operands(5, 2),
            new Operands(5, 3),
            new Operands(5, 4),
            new Operands(6, 1),
            new Operands(6, 2),
            new Operands(6, 3),
            new Operands(7, 1),
            new Operands(7, 2),
            new Operands(8, 1),
            new Operands(2, 3),
            new Operands(2, 4),
            new Operands(2, 5),
            new Operands(2, 6),
            new Operands(2, 7),
            new Operands(3, 2),
            new Operands(3, 4),
            new Operands(3, 5),
            new Operands(3, 6),
            new Operands(4, 2),
            new Operands(4, 3),
            new Operands(4, 5),
            new Operands(5, 2),
            new Operands(5, 3),
            new Operands(5, 4),
            new Operands(6, 2),
            new Operands(6, 3),
            new Operands(7, 2),
            new Operands(1, 9),
            new Operands(2, 8),
            new Operands(3, 7),
            new Operands(4, 6),
            new Operands(5, 5),
            new Operands(6, 4),
            new Operands(7, 3),
            new Operands(8, 2),
            new Operands(9, 1),
            new Operands(2, 8),
            new Operands(3, 7),
            new Operands(4, 6),
            new Operands(6, 4),
            new Operands(7, 3),
            new Operands(8, 2)
        };
    }
}
